### ISSUE TITLE
DI: zdokumentovat chained syntax

### ISSUE THREAD

**Issue by klimesf** [nette/docs#228]

**Comment by f3l1x** [comment]
I'm not sure what do you mean.

Something like this?

```yaml
services:
  foobar:
    class: Foobar
    setup: 
      - call::by::me(%debugMode%)
```

WDYT @dg?
