### ISSUE TITLE
Rozsireni: prefix u sluzeb v neonu

### ISSUE THREAD

**Issue by matej21** [nette/docs#377]
https://doc.nette.org/cs/2.3/di-extensions#toc-nacitani-dodatecne-konfigurace
https://forum.nette.org/cs/24225-konfiguracni-soubor-k-extension-a-prefixovani-v-nem

**Comment by greeny** [comment]
Problem still persist, since there are references to services through @ notation (e.g. @blog.articles)

**Comment by Majkl578** [comment]
ping @matej21

**Comment by matej21** [comment]
I'm afraid there is currently no solution. Maybe we should revert it for now.

**Comment by greeny** [comment]
My idea:
1) remove dynamic references completely (all @connection and @blog.foo references)
2) add a note that DI Container will autowire parameters with typehint
3) add a paragraph (or another note) where will be shown, how to wire parameters without typehint (basically the thing we removed in point 1 )
ping @matej21

**Comment by f3l1x** [comment]
IMHO we can reference to other service with FQN, right @matej21?

**Comment by dg** [comment]
Imho solved by https://github.com/nette/di/pull/85

**Comment by f3l1x** [comment]
It looks like it's solved in code but not in docs, right?

**Comment by f3l1x** [comment]
```yaml
services:
	articles:
		factory: MyBlog\ArticlesModel(@connection)

	comments:
		factory: MyBlog\CommentsModel(@connection, @blog.articles)

	articlesList:
		factory: MyBlog\Components\ArticlesList(@blog.articles)
```

to:

```yaml
services:
	articles:
		factory: MyBlog\ArticlesModel(@connection)

	comments:
		factory: MyBlog\CommentsModel(@connection, @extension.articles)

	articlesList:
		factory: MyBlog\Components\ArticlesList(@extension.articles)
```
