### ISSUE TITLE
DI: document autowiring options (no, self, interface)

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#493]
Leave a not about autowiring.

- [x] autowired: no
```yaml
services:
    mailer:
        factory: SpecialMailer
        autowired: no
```

- [ ] autowired: self
```yaml
services:
    mailer:
        factory: SpecialMailer
        # inject to services which explicit require SpecialMailer
        autowired: self
```
- [x] autowired: [class, interface]
```yaml
services:
    mailer:
        factory: SpecialMailer
        # inject to services which explicit require 
        # SpecialMailer or SpecialMailerInterface
        autowired: [SpecialMailerInterface]
        autowired: [SpecialMailer, SpecialMailerInterface]
```

Maybe only for nette 2.4.
