### ISSUE TITLE
DI: document alteration option for service

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#494]
```yaml
services:
    cache.storage:
        alteration: yes
        setup:
            - setFoo('bar')
```
