### ISSUE TITLE
DI - remove deprecated extending service

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#528]
According to forum post: https://forum.nette.org/cs/28875-dedeni-sluzeb-spatne-odsazeni-bad-indentation

```yaml
services:
    myConnection < nette.database.default:
        setup:
            $onQuery: [ @logger::log ]
```
